

default_platform(:android)

platform :android do
  desc "Labe for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:177216652429:android:d485ffa143adade88a4ec4",
      firebase_cli_token: EVN["FIREBASE_CLI_TOKEN"],
      android_artifact_type:"APK",
      android_artifact_path:"../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "aladwymahmoud@gmail.com",
      release_notes: "First Fastlane Firebase Distribution"
    )
  end
end
